apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kpulse.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "kpulse.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels: {{- include "kpulse.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "kpulse.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
{{ toYaml . | indent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "kpulse.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: kpulse
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["--config=/etc/kpulse/config.yaml", "--secrets=/etc/kpulse/secrets"]
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet: { path: /readyz, port: 8080 }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 10
          resources: {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - { name: config, mountPath: /etc/kpulse }
            - { name: secrets, mountPath: /etc/kpulse/secrets, readOnly: true }
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
      volumes:
        - name: config
          configMap:
            name: {{ include "kpulse.fullname" . }}-config
            items: [{ key: config.yaml, path: config.yaml }]
        - name: secrets
          secret:
            secretName: {{ include "kpulse.fullname" . }}-secrets
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
