apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kpulse.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels: {{- include "kpulse.labels" . | nindent 4 }}
type: Opaque
{{- with .Values.channels.secrets }}
stringData:
{{- range $k, $v := . }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- else }}
stringData:
  PLACEHOLDER: "set channels.secrets in values.yaml to populate this"
{{- end }}
